POST https://floral-star-5078.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Drug Asanovic",
    "number": "07-31-30940"
}

###
GET https://floral-star-5078.fly.dev/api/persons

###
DELETE https://floral-star-5078.fly.dev/api/persons/2